#!/bin/bash

cd orig

shopt -s nullglob

for name in *.c; do
    echo "Processing file: $name"
    printf "#include <stdlib.h>\n" | cat - $name | sed '/void \* /s//\/\/&/' | sed '/extern void/s//\/\/&/' | sed '/void * __attribute/s//\/\/&/' | sed '/#define __VERIFIER_assert/s//\/\/&/' | sed "s/([^)]*) *malloc/malloc/g" | cpp -E -I . -o ../preprocessed/"$name"
done
