#!/bin/sh

LAZABS=../../tricera/tri

cd preprocessed

unsoundCount=0
impreciseCount=0
matchCount=0
safeMatchCount=0
unsafeMatchCount=0
errorCount=0

for name in *.c 
do
    echo
    echo $name
    res=$($LAZABS -cex -abstract:off -t:60 "$@" $name 2>&1 | grep -v 'at ')
    echo
    echo "$res"

    ymlExpected=$(sed -nr '/expected_verdict:/ s/.*expected_verdict:([^"]+).*/\1/p' ../yml/${name%?}yml | head -1)
    if echo "$ymlExpected" | grep -q "false"; then
        expected="UNSAFE"
    else
        expected="SAFE"
    fi       
    
    echo "Expected result: $expected"

    totalCount=$((totalCount+1))

    if echo "$res" | grep -qw "$expected"; then
        echo "results match!"
        matchCount=$((matchCount+1))
        if [ "$expected" = "UNSAFE" ]; then
            unsafeMatchCount=$((unsafeMatchCount+1))
        else
            safeMatchCount=$((safeMatchCount+1))
        fi
    else

        echo "results do not match!"
        if [ "$expected" = "UNSAFE" ]; then
            if echo "$res" | grep -qw "SAFE"; then
                unsoundCount=$((unsoundCount+1))
                echo "UNSOUND RESULT DETECTED!"
            else
                errorCount=$((errorCount+1))
                echo "PARSING ERROR OR BUG DETECTED"
            fi
        else #expected result is SAFE
            if echo "$res" | grep -qw "UNSAFE"; then
                impreciseCount=$((impreciseCount+1))
            else
                errorCount=$((errorCount+1))
                echo "PARSING ERROR OR BUG DETECTED"
            fi
        fi
    fi
    echo
    echo "---------------------------"
    echo "matched    : $matchCount"
    echo "  -safe    : $safeMatchCount"
    echo "  -unsafe  : $unsafeMatchCount"
    echo "---------------------------"
    echo "imprecise  : $impreciseCount"
    echo "unsound    : $unsoundCount"
    echo "error      : $errorCount"
    echo "---------------------------"
    echo "total      : $totalCount"
    echo "---------------------------"
done
cd ..
